# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(762, 525)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 20, 391, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 200, 161, 61))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 280, 161, 41))
        self.pushButton.setStyleSheet("font: 11pt \"MS Reference Sans Serif\";\n"
"color: rgb(10, 102, 53);\n"
"background-color: rgb(207, 255, 156);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 350, 351, 41))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("font: 11pt \"MS Reference Sans Serif\";\n"
"color: rgb(10, 102, 53);\n"
"background-color: rgb(207, 255, 156);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 420, 351, 41))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("font: 11pt \"MS Reference Sans Serif\";\n"
"color: rgb(10, 102, 53);\n"
"background-color: rgb(207, 255, 156);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 10, 741, 251))
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 470, 61, 31))
        self.pushButton_4.setStyleSheet("font: 75 8pt \"MS Sans Serif\";\n"
"background-color: rgb(197, 27, 5);\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00aa00;\">ОЦЕНКА ПИЩЕВОГО СТАТУСА</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#4d7c14;\">Функции:</span></p></body></html>"))
        self.pushButton.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Индекс массы тела</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Индекс массы тела"))
        self.pushButton_2.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Норма ещедневного потребления калорий</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Норма ежедневного потребления калорий "))
        self.pushButton_3.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Норма ещедневного потребления калорий</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "Оценка по белкам, жирам и углеводам"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic; text-decoration: underline; color:#0e3532;\">Добро пожаловать! </span></p><p><span style=\" font-size:14pt; font-style:italic; text-decoration: underline; color:#0e3532;\">Здесь вы сможете легко и удобно отслеживать свой пищевой режим,</span></p><p><span style=\" font-size:14pt; font-style:italic; text-decoration: underline; color:#0e3532;\">выявлять возможные недостатки и достичь оптимального состояния </span></p><p><span style=\" font-size:14pt; font-style:italic; text-decoration: underline; color:#0e3532;\">своего организма!</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Dialog", "Выйти"))
